config/routes.rb
Rails.application.routes.draw do
  resources :elevators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/elevator.rb
class Elevator < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  before_action :set_elevator, only: [:show, :edit, :update, :destroy]

  # GET /elevators
  # GET /elevators.json
  def index
    @elevators = Elevator.all
  end

  # GET /elevators/1
  # GET /elevators/1.json
  def show
  end

  # GET /elevators/new
  def new
    @elevator = Elevator.new
  end

  # GET /elevators/1/edit
  def edit
  end

  # POST /elevators
  # POST /elevators.json
  def create
    @elevator = Elevator.new(elevator_params)

    respond_to do |format|
      if @elevator.save
        format.html { redirect_to @elevator, notice: 'Elevator was successfully created.' }
        format.json { render :show, status: :created, location: @elevator }
      else
        format.html { render :new }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevators/1
  # PATCH/PUT /elevators/1.json
  def update
    respond_to do |format|
      if @elevator.update(elevator_params)
        format.html { redirect_to @elevator, notice: 'Elevator was successfully updated.' }
        format.json { render :show, status: :ok, location: @elevator }
      else
        format.html { render :edit }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevators/1
  # DELETE /elevators/1.json
  def destroy
    @elevator.destroy
    respond_to do |format|
      format.html { redirect_to elevators_url, notice: 'Elevator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator
      @elevator = Elevator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elevator_params
      params.require(:elevator).permit(:needs, :client, :product_name, :category, :value, :conflict, :difference)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/views/elevators/_form.html.erb
<%= form_with(model: elevator, local: true) do |form| %>
  <% if elevator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul>
      <% elevator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :needs %>
    <label>どんなニーズ、課題に対応する？</label>
    <%= form.text_field :needs %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <label>顧客、ターゲットは誰？</label>
    <%= form.text_field :client %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <label>プロダクト名称は？</label>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <label>プロダクトのカテゴリは？どのジャンルに属する？</label>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <label>ユーザーが得られる価値は？なぜそのアプリを使用する？</label>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :conflict %>
    <label>競合しているアプリ、ソフトは？</label>
    <%= form.text_field :conflict %>
  </div>

  <div class="field">
    <%= form.label :difference %>
    <label>競合との差別化している部分は？このプロフダクトにしかないものは？</label>
    <%= form.text_field :difference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elevators/edit.html.erb
<h1>Editing Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Show', @elevator %> |
<%= link_to 'Back', elevators_path %>

app/views/elevators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elevators</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <tr>
        <td><%= elevator.product_name %></td>
        <td><%= link_to 'Show', elevator %></td>
        <td><%= link_to 'Edit', edit_elevator_path(elevator) %></td>
        <td><%= link_to 'Destroy', elevator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elevator', new_elevator_path %>

app/views/elevators/new.html.erb
<h1>New Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Back', elevators_path %>

app/views/elevators/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li>
    [ <%= @elevator.needs %> ]したい
  </li>
  <li>
    [ <%= @elevator.client %> ]向けの、
  </li>
  <li>
    [ <%= @elevator.product_name %> ]というプロダクトは、
  </li>
  <li>
    [ <%= @elevator.category %> ]です。
  </li>
  <li>
    これは[ <%= @elevator.value %> ]ができ、
  </li>
  <li>
    [ <%= @elevator.conflict %> ]とは違って、
  </li>
  <li>
    [ <%= @elevator.difference %> ]が備わっている。
  </li>
</ul>

<%= link_to 'Edit', edit_elevator_path(@elevator) %> |
<%= link_to 'Back', elevators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NElevatorPitch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>